# Generated by Django 3.1.1 on 2020-10-16 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='package',
            new_name='services',
        ),
    ]
