# Generated by Django 3.1.1 on 2020-10-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profilelineitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilelineitem',
            name='services',
        ),
        migrations.AddField(
            model_name='profilelineitem',
            name='remaining_email_addresses',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profilelineitem',
            name='remaining_pages',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profilelineitem',
            name='remaining_seo_updates',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='profilelineitem',
            name='remaining_website_updates',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
