# Generated by Django 3.1.1 on 2020-10-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20201018_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='services',
        ),
        migrations.AlterField(
            model_name='profilelineitem',
            name='remaining_email_addresses',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profilelineitem',
            name='remaining_pages',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profilelineitem',
            name='remaining_seo_updates',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profilelineitem',
            name='remaining_website_updates',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
