# Generated by Django 3.1.1 on 2020-10-18 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_auto_20201018_1038'),
        ('profiles', '0006_auto_20201018_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilelineitem',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.package'),
        ),
    ]
