# Generated by Django 3.1.1 on 2020-10-19 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_services'),
        ('profiles', '0008_auto_20201018_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilelineitem',
            name='remaining_email_addresses',
        ),
        migrations.RemoveField(
            model_name='profilelineitem',
            name='remaining_pages',
        ),
        migrations.RemoveField(
            model_name='profilelineitem',
            name='remaining_seo_updates',
        ),
        migrations.RemoveField(
            model_name='profilelineitem',
            name='remaining_website_updates',
        ),
        migrations.AddField(
            model_name='profilelineitem',
            name='services',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.services'),
        ),
    ]
