# Generated by Django 3.1.1 on 2020-10-25 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_auto_20201018_1038'),
        ('profiles', '0011_auto_20201024_1833'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileLineItem',
            new_name='ProfileLineItems',
        ),
    ]
