# Generated by Django 3.1.1 on 2020-09-12 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Package',
        ),
    ]
