# Generated by Django 3.1.1 on 2020-10-18 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_auto_20201018_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='remaining_email_addresses',
        ),
        migrations.RemoveField(
            model_name='package',
            name='remaining_pages',
        ),
        migrations.RemoveField(
            model_name='package',
            name='remaining_seo_updates',
        ),
        migrations.RemoveField(
            model_name='package',
            name='remaining_website_updates',
        ),
    ]
