# Generated by Django 3.1.1 on 2020-10-19 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20201019_1924'),
        ('services', '0003_services'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Services',
        ),
    ]
