# Generated by Django 3.1.1 on 2020-10-24 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0004_auto_20201018_1038'),
        ('profiles', '0011_auto_20201024_1833'),
        ('services', '0004_delete_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_pages', models.PositiveSmallIntegerField(default=0, null=True)),
                ('remaining_email_addresses', models.PositiveSmallIntegerField(default=0, null=True)),
                ('remaining_seo_updates', models.PositiveSmallIntegerField(default=0, null=True)),
                ('remaining_website_updates', models.PositiveSmallIntegerField(default=0, null=True)),
                ('package', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.package')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userservices', to='profiles.userprofile')),
            ],
        ),
    ]
