# Generated by Django 3.1.1 on 2020-10-25 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20201024_1833'),
        ('packages', '0004_auto_20201018_1038'),
        ('services', '0005_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='packages.package'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile'),
        ),
    ]
