# Generated by Django 3.1.1 on 2020-10-25 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_details', '0005_auto_20201024_1449'),
        ('services', '0006_auto_20201025_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website_details.website'),
        ),
    ]
