# Generated by Django 3.1.1 on 2020-10-25 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_services_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='website',
        ),
    ]
