# Generated by Django 3.1.1 on 2020-10-27 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_remove_services_website'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Services'},
        ),
    ]
