# Generated by Django 3.1.1 on 2020-09-22 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('checkout', '0008_auto_20200922_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=1, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='profiles.userprofile'),
            preserve_default=1,
        ),
    ]
