# Generated by Django 3.1.1 on 2020-10-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_description', models.TextField()),
                ('current_url', models.TextField(blank=True, max_length=100, null=True)),
                ('new_site_description', models.TextField()),
            ],
        ),
    ]
