# Generated by Django 3.1.1 on 2020-10-24 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20201019_1924'),
        ('website_details', '0002_auto_20201024_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=1, on_delete=django.db.models.deletion.SET_NULL, related_name='websites', to='profiles.userprofile'),
            preserve_default=1,
        ),
    ]
