# Generated by Django 3.1.1 on 2020-10-24 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20201019_1924'),
        ('website_details', '0003_website_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='user_profile',
            field=models.ForeignKey(null=1, on_delete=django.db.models.deletion.SET_NULL, related_name='websites', to='profiles.userprofile'),
        ),
    ]
