# Generated by Django 3.1.1 on 2020-10-25 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20201024_1833'),
        ('services', '0008_remove_services_website'),
        ('website_details', '0005_auto_20201024_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='services',
            field=models.ForeignKey(blank=True, null=1, on_delete=django.db.models.deletion.SET_NULL, to='services.services'),
            preserve_default=1,
        ),
        migrations.AlterField(
            model_name='website',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=1, on_delete=django.db.models.deletion.SET_NULL, to='profiles.userprofile'),
        ),
    ]
